version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-iam-role-trust-policy-check"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dqun0a8ai2v6"
s3_prefix = "aws-sam-iam-role-trust-policy-check"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
